name: hijacking2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - pip:
      - absl-py==2.2.2
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - bert-score==0.3.13
      - bitsandbytes==0.41.1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==3.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - filelock==3.16.1
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - huggingface-hub==0.29.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - langdetect==1.0.9
      - lxml==5.3.1
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - moverscore==1.0.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.0
      - nltk==3.9.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - packaging==24.2
      - pandas==2.0.3
      - peft==0.7.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - portalocker==3.0.0
      - propcache==0.2.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rouge-score==0.1.2
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - safetensors==0.5.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==3.0.0
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.2.3
      - wandb==0.19.8
      - werkzeug==3.0.6
      - xxhash==3.5.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /work/shovon/.conda/envs/hijacking2
